### ISSUE TITLE
Wiser support

### ISSUE THREAD

**Issue by NovaGL** [cburn/cgate2mqtt#1]
Hi,

Can this use Wiser as C-Gate to push topics?

**Comment by cburn** [comment]
Hi, I don't own a Wiser so I'm not 100% sure. 
cgate2mqtt needs cgate to be running and connected to a CNI or PCI.

From what I've read you can connect cgate to the Wiser's inbuilt CNI, but then you would lose all functionality of the Wiser as it's no longer connected to cbus :(

So you're better off with a dedicated CNI or PCI.

**Comment by NovaGL** [comment]
I believe the wiser 2 has both. Just want to know the easiest way. Thanks. If you find a way using Wiser 2 let me know

**Comment by NovaGL** [comment]
Where do I enter the IP and Port of the C-Gate for this to work.

**Comment by cburn** [comment]
Edit cgate2mqtt.tac line 106 & 107, change the 'localhost' to your host name/ip addr :

```
STATUS_EP = clientFromString(reactor, "tcp:localhost:20025")
COMMAND_EP = clientFromString(reactor, "tcp:localhost:20023")
```

and set the mqtt server on line 117 : 

```
mqtt_service = MQTTService(clientFromString(reactor, "tcp:localhost:1883"),
```

**Comment by NovaGL** [comment]
Hi,

I'm getting this error now. Any ideas
 cannot import name python_2_unicode_compatible
